stages:
  - build
  - notify

build-frontend-code-job:
  stage: build  
  only:
    changes:
    - "frontend/*"
  script:        
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/frontend

telegram-notification-frontend:
  stage: notify
  needs:
    - job: build-frontend-code-job
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notification/
  script: |
      curl -X POST -H "Content-type: application/json" \
      --data "{\"chat_id\": \"6342685754\", \"text\": \"Павел Науменко собрал frontend. URL: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build-frontend-code-job\"}" \
      https://api.telegram.org/bot6342685754:AAGYs_X-HXuc627KOHsuD1BNM_sNW2okzGk/sendMessage

  