stages:
  - build

build-frontend-image:
  stage: build
  image: alpine:3.18
  script:
    - echo "test"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "$frontend/Dockerfile_frontend"
      --destination "${CI_REGISTRY_IMAGE}/sausage-frontend:latest"
      --build-arg VERSION=$VERSION
      --cache=true
  only:
     changes:
     - frontend/**/*
