stages:
  - build

build-frontend-image:
  stage: build
  image: ubuntu:latest
  before_script: 
  - |
    apt update
    apt install curl
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh ./get-docker.sh --dry-run -y
  script:
    - docker build -t ${DOCKERHUB_USERNAME}/sausage-frontend:latest -f infra/Dockerfile_frontend .
    - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
    - docker push ${DOCKERHUB_USERNAME}/sausage-frontend:latest
  only:
     changes:
     - frontend/**/*
