stages:
  - build
  - notify

build-frontend-code-job:
  stage: build  
  only:
    changes:
    - frontend/*
  script:        
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/frontend

telegram-notification-frontend:
  stage: notify
  needs:
    - build-frontend-code-job
  rules:
    - exists:
        - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - |
      sh curl -X POST -H "Content-type: application/json" \
      --data "{\"chat_id\": \"-1002056379103\", \"text\": \"Павел Науменко собрал frontend. URL: $CI_PROJECT_URL/-/jobs/artifacts/sausage-store-0.0.1/sausage-store-0.0.1/public_html?job=build-backend-code-job\"}" \
      https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage
  