stages:
  - build
  - notify

build-frontend-code-job:
  stage: build  
  only:
    changes:
    - "frontend/*"
  script:        
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/frontend

telegram-notification-frontend:
  stage: notify
  needs:
    - job: build-frontend-code-job
      artifacts: true
  rules:
    - exists:
        - $CI_COMMIT_MESSAGE =~ /send notification/
  script: |
      ls
  