stages:
  - module-pipelines

cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository
    - .npm/

frontend:
  stage: module-pipelines
  trigger:
    include: "frontend/.gitlab-ci.yml"
    strategy: depend

backend:
  stage: module-pipelines
  trigger:
    include: "backend/.gitlab-ci.yml"
    strategy: depend 

