stages:
  - module-pipelines
  - deploy

frontend:
  stage: module-pipelines
  trigger:
    include: "frontend/.gitlab-ci.yml"
    strategy: depend

backend:
  stage: module-pipelines
  trigger:
    include: "backend/.gitlab-ci.yml"
    strategy: depend 

