stages:
  - build

services:
  - docker:dind

build-backend-image:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "test"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/infra"
      --dockerfile "${CI_PROJECT_DIR}/infra/Dockerfile_backend"
      --destination "${CI_REGISTRY_IMAGE}/sausage-backend:latest"
      --build-arg VERSION=$VERSION
      --cache=true
  only:
     changes:
     - backend/**/*
