stages:
  - build
  - notify


build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar


telegram-notification-backend:
  stage: notify
  needs:
    - job: build-backend-code-job
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /notification/
  script: |
      curl -X POST -H "Content-type: application/json" \
      --data "{\"chat_id\": \"6342685754\", \"text\": \"Павел Науменко собрал backend. URL: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build-backend-code-job\"}" \
      https://api.telegram.org/bot6342685754:AAGYs_X-HXuc627KOHsuD1BNM_sNW2okzGk/sendMessage
