stages:
  - build

build-backend-image:
  stage: build
  script:
    - docker build -t ${DOCKERHUB_USERNAME}/sausage-backend:latest -f infra/Dockerfile_backend .
    - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
    - docker push ${DOCKERHUB_USERNAME}/sausage-backend:latest
  only:
     changes:
     - backend/**/*