include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test

build-backend-image:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/infra/Dockerfile_backend"
      --destination "${CI_REGISTRY_IMAGE}/sausage-backend:latest"
      --build-arg VERSION=$VERSION
      --cache=true

spotbugs-sast:
  stage: test
  needs:
    - job: build-backend-image
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository

