stages:
  - build
  - notify


build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
  variables:
    NEEDS_JOB: "$CI_JOB_NAME"


telegram-notification-backend:
  stage: notify
  needs:
    - job: build-backend-code-job
      variables: true
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /notification/
  script: |
      curl -X POST -H "Content-type: application/json" \
      --data "{\"chat_id\": \"-1002056379103\", \"text\": \"Павел Науменко собрал backend. URL: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=$NEEDS_JOB\"}" \
      https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage
