stages:
  - build

services:
  - docker:dind

build-backend-image:
  stage: build
  image: alpine:3.18
  script:
    - apk add curl
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sh get-docker.sh
    - sudo docker build -t ${DOCKERHUB_USERNAME}/sausage-backend:latest -f infra/Dockerfile_backend .
    - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
    - sudo docker push ${DOCKERHUB_USERNAME}/sausage-backend:latest
  only:
     changes:
     - backend/**/*
