stages:
  - build

build-backend-image:
  stage: build
  image: ubuntu:latest
  before_script: 
  - |
    apt update
    apt install curl
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh | yes Y
  script:
    - docker build -t ${DOCKERHUB_USERNAME}/sausage-backend:latest -f infra/Dockerfile_backend .
    - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
    - docker push ${DOCKERHUB_USERNAME}/sausage-backend:latest
  only:
     changes:
     - backend/**/*
