include:
  - template: Security/SAST.gitlab-ci.yml

variables:
   VERSION: 1.0.${CI_PIPELINE_ID}
   MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
   JAVA_OPTS: -XX:MaxRAMPercentage=90

stages:
  - build
  - test
  - notify

build-backend-image:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/infra/Dockerfile_backend"
      --destination "${CI_REGISTRY_IMAGE}/sausage-backend:latest"
      --build-arg VERSION=$VERSION
      --cache=true

spotbugs-sast:
  stage: test
  needs:
    - job: build-backend-image
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository

sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  needs:
    - job: build-backend-image
  script: |
    cd backend/
    mvn verify sonar:sonar \
    -Dsonar.host.url=$SONARQUBE_URL \
    -Dsonar.projectKey=$SONAR_PROJECT_KEY_BACK \
    -Dsonar.login=$SONAR_LOGIN_BACKEND \
    -Dsonar.qualitygate.wait=true

telegram-notification-backend:
  stage: notify
  needs:
    - job: sonarqube-backend-sast
    - job: spotbugs-sast
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /notification/
  script: |
    curl -X POST -H "Content-type: application/json" \
    --data "{\"chat_id\": \"-1002056379103\", \"text\": \"Павел Науменко собрал и протестировал backend by sast and sonarqube. URL: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build-backend-code-job\"}" \
    https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage



