stages:
  - build
  - notify

build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar


telegram-notification-backend:
  stage: notify
  needs:
    - job: build-backend-code-job
  rules:
    - if $CI_COMMIT_MESSAGE =~ /notification/
  script:
    - echo "Sending notification"

