volumes:
  frontend_volume:

services:
  sausage-backend:
    container_name: sausage-backend
    build:
      context: ../
      dockerfile: infra/Dockerfile_backend
    env_file:
      - .env
    expose:
      - 8080

  sausage-frontend:
    container_name: sausage-frontend
    build:
      context: ../
      dockerfile: infra/Dockerfile_frontend
    env_file:
      - .env
    volumes:
      - frontend_volume:/app/frontend
    expose:
      - 8080

  nginx:
    container_name: nginx
    depends_on:
      - sausage-backend
      - sausage-frontend
    restart: unless-stopped
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_volume:/opt/monitoring/frontend/build/ 
    ports:
      - "80:80"



