volumes:
  frontend_volume:

services:
  backend-blue: &backend
    container_name: backend-blue
    build:
      context: ../
      dockerfile: infra/Dockerfile_backend
    env_file:
      - .env
    expose:
      - 8080
    healthcheck:
      test: curl http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6

  backend-green:
    <<: *backend
    container_name: backend-green

  sausage-backend-report:
    container_name: backend-report
    build:
      context: ../
      dockerfile: infra/Dockerfile_backend_report
    environment:
      DB: ${SPRING_DATA_MONGODB_URI}
      PORT: 8080
    expose:
      - 8080

  sausage-frontend:
    container_name: sausage-frontend
    depends_on:
      - minio
    build:
      context: ../
      dockerfile: infra/Dockerfile_frontend
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: sausage-store
    ports:
      - "80:80"

  minio:
    image:  quay.io/minio/minio:RELEASE.2023-07-11T21-29-34Z
    container_name: minio
    command: server /data --console-address ":9001"
    restart: always
    volumes:
      - /home/student/minio/data:/data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3 
