volumes:
  frontend_volume:

services:
  sausage-backend:
    container_name: sausage-backend
    image: ghostblade3301/sausage_backend:latest
    env_file:
      - .env
    expose:
      - 8080

  sausage-frontend:
    container_name: sausage-frontend
    image: ghostblade3301/sausage_frontend:latest
    env_file:
      - .env
    volumes:
      - frontend_volume:/app/frontend
    expose:
      - 8080

  nginx:
    container_name: nginx
    depends_on:
      - sausage-backend
      - sausage-frontend
    restart: unless-stopped
    image: nginx:1.25
    volumes:
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf
      - frontend_volume:/opt/monitoring/frontend/build/ 
    ports:
      - "80:80"



