FROM node:16.20.0-alpine3.18 as builder
WORKDIR /usr/src/app
COPY ./frontend .
RUN npm ci && npm run build

FROM nginxproxy/nginx-proxy
WORKDIR /app
COPY ./infra/nginx.tmpl ./
COPY --from=builder /usr/src/app/dist/frontend /opt/monitoring/frontend/build/